<a href="https://colab.research.google.com/github/Sangeetha231005/MLops-training/blob/main/One_Hot_Encoding_Flood_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**One Hot Encoding - Flood Detection**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:

df = pd.read_csv(
    '/content/drive/MyDrive/Flood_detection/flood_dataset.csv',
    low_memory=False
)

In [ ]:
df.head()

,gsim_code,latitude,longitude,year,Annual peak discharge,Unit peak discharge,country,countryname,continentcode,Annual Mean Temperature,...,SecondThird Bifurcationratio,ThirdForth Bifurcationratio,FourthFifth Bifurcationratio,FifthSixth Bifurcationratio,Sixthseventh Bifurcationratio,Number of Dams,Climate Type,Landcover Type,Soil Type,Lithology Type
0,AR_0000002,-25.28,-65.38,1944,329.364,0.046985,AR,Argentina,SA,11.373328,...,4.8,5.0,NaN,NaN,NaN,0,Warm Temperate,No dominant class,No dominant class,Metamorphics
1,AR_0000002,-25.28,-65.38,1963,519.160,0.074061,AR,Argentina,SA,11.373328,...,4.8,5.0,NaN,NaN,NaN,0,Warm Temperate,No dominant class,No dominant class,Metamorphics
2,AR_0000002,-25.28,-65.38,1965,367.600,0.052440,AR,Argentina,SA,11.373328,...,4.8,5.0,NaN,NaN,NaN,0,Warm Temperate,No dominant class,No dominant class,Metamorphics
3,AR_0000017,-27.40,-65.98,1956,60.150,0.069699,AR,Argentina,SA,13.961597,...,2.0,NaN,NaN,NaN,NaN,0,Arid,No dominant class,Cambisols,Unconsolidated sediments
4,AR_0000017,-27.40,-65.98,1960,74.620,0.086466,AR,Argentina,SA,13.961597,...,2.0,NaN,NaN,NaN,NaN,0,Arid,No dominant class,Cambisols,Unconsolidated sediments

In [ ]:
df = df.drop([
    'gsim_code',
    'countryname',
    'continentcode',
    'year'
], axis=1)

In [ ]:
df.shape

(45932, 89)

In [ ]:
df.isnull().sum()

latitude                    0
longitude                   0
Annual peak discharge       0
Unit peak discharge         0
country                    74
                         ...
Number of Dams              0
Climate Type                0
Landcover Type             52
Soil Type                1494
Lithology Type           1222
Length: 89, dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage)

latitude                 0.000000
longitude                0.000000
Annual peak discharge    0.000000
Unit peak discharge      0.000000
country                  0.161108
                           ...
Number of Dams           0.000000
Climate Type             0.000000
Landcover Type           0.113211
Soil Type                3.252634
Lithology Type           2.660455
Length: 89, dtype: float64

In [ ]:
df = df.loc[:, missing_percentage < 50]

In [ ]:
df.shape

(45932, 69)

In [ ]:
df.isnull().sum()

latitude                    0
longitude                   0
Annual peak discharge       0
Unit peak discharge         0
country                    74
                         ...
Number of Dams              0
Climate Type                0
Landcover Type             52
Soil Type                1494
Lithology Type           1222
Length: 69, dtype: int64

In [ ]:
df = df.fillna(df.mean(numeric_only=True))

In [ ]:
df = df.fillna('Unknown')

In [ ]:
df.dtypes

latitude                 float64
longitude                float64
Annual peak discharge    float64
Unit peak discharge      float64
country                   object
                          ...
Number of Dams             int64
Climate Type              object
Landcover Type            object
Soil Type                 object
Lithology Type            object
Length: 69, dtype: object

In [ ]:
categorical_columns = df.select_dtypes(include=['object']).columns
print(categorical_columns)

Index(['country', 'Climate Type', 'Landcover Type', 'Soil Type',
       'Lithology Type'],
      dtype='object')

In [ ]:
df = pd.get_dummies(
    df,
    columns=[
        'country',
        'Climate Type',
        'Landcover Type',
        'Soil Type',
        'Lithology Type'
    ]
)

In [ ]:
df.head()

,latitude,longitude,Annual peak discharge,Unit peak discharge,Annual Mean Temperature,Mean Diurnal Range,Isothermality,Temperature Seasonality,Max Temperature of Warmest Month,Min Temperature of Coldest Month,...,Lithology Type_Intermediate volcanic rocks,Lithology Type_Metamorphics,Lithology Type_Mixed sedimentary rocks,Lithology Type_No Data,Lithology Type_No dominant class,Lithology Type_Pyroclastics,Lithology Type_Siliciclastic sedimentary rocks,Lithology Type_Unconsolidated sediments,Lithology Type_Unknown,Lithology Type_Water Bodies
0,-25.28,-65.38,329.364,0.046985,11.373328,14.494187,58.613892,369.461182,22.68236,-2.082603,...,False,True,False,False,False,False,False,False,False,False
1,-25.28,-65.38,519.160,0.074061,11.373328,14.494187,58.613892,369.461182,22.68236,-2.082603,...,False,True,False,False,False,False,False,False,False,False
2,-25.28,-65.38,367.600,0.052440,11.373328,14.494187,58.613892,369.461182,22.68236,-2.082603,...,False,True,False,False,False,False,False,False,False,False
3,-27.40,-65.98,60.150,0.069699,13.961597,14.924928,54.608349,462.010681,26.57007,-0.854799,...,False,False,False,False,False,False,False,True,False,False
4,-27.40,-65.98,74.620,0.086466,13.961597,14.924928,54.608349,462.010681,26.57007,-0.854799,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
X = df[[
    'latitude',
    'longitude',
    'Annual Mean Temperature',
    'Annual Precipitation',
    'Drainage Area',
    'Basin Relief',
    'Drainage Density',
    'Number of Dams'
]]

In [ ]:
y = df['Annual peak discharge']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10
)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)
print(predictions)

[675.25377894  98.77452942  -9.18382344 ...  99.45516238 305.06458751
 401.46713529]

In [ ]:
model.score(X_test, y_test)

0.04911596977323296